#!/bin/bash
#### CONFIG FILE FOR ROVS SCRIPTS ####
#Github
GITUSER="danielroviratorres@gmail.com"
GITNAME="Daniel"

#Folders
HD="$HOME/HD"
GD="$HOME/gdrive"
SCRIPTS="$HOME/scripts"

# Rom names/folder
ROM1="lineage"
ROM2=""
ROM3=""

# Shutdown time
TIME="2"

# Ccache size
CSIZE="100G"
