# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/nairo/setup-makefiles.sh

# Dex
# Don't dex preopt prebuilt apps that will be updated from Play Store
DONT_DEXPREOPT_PREBUILTS := true
# Don't uncompress dex files in priv apps APKs to save on space.
DONT_UNCOMPRESS_PRIV_APPS_DEXS := true

